name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - dev
  pull_request:
jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.6
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsnmp-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
